name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Test-1
      run: ls -al
    - name: Test
      run: cd ./net-core-demo/TestLib
    - name: Test2
      run: ls -al
    - name: Build
      run: dotnet build -c Release -o ./app/Release
